package main

import (
	"fmt"
	"testing"
	"time"
	"github.com/WaekCode/Pokedex/internal/pokecache"
)

func TestCleanInput(t *testing.T) {

	cases := []struct {
		input    string
		expected []string
	}{
		{
			input:    "  ",
			expected: []string{},
		},
		{
			input:    "  hello  ",
			expected: []string{"hello"},
		},
		{
			input:    "  hello  world  ",
			expected: []string{"hello", "world"},
		},
		{
			input:    "  HellO  World  ",
			expected: []string{"hello", "world"},
		},
	}

	for _, c := range cases {
		actual := cleanInput(c.input)

		// Check length first
		if len(actual) != len(c.expected) {
			t.Errorf("cleanInput(%q) = %v; want %v", c.input, actual, c.expected)
			continue
		}

		// Compare each word
		for i := range actual {
			word := actual[i]
			expectedWord := c.expected[i]

			if word != expectedWord {
				t.Errorf("input %q: at index %d, expected %q, got %q",
					c.input,
					i,
					expectedWord,
					word)
			}
		}
	}
}

func TestAddGet(t *testing.T) {
	const interval = 5 * time.Second
	cases := []struct {
		key string
		val []byte
	}{
		{
			key: "https://example.com",
			val: []byte("testdata"),
		},
		{
			key: "https://example.com/path",
			val: []byte("moretestdata"),
		},
	}

	for i, c := range cases {
		t.Run(fmt.Sprintf("Test case %v", i), func(t *testing.T) {
			cache := pokecache.NewCache(interval)
			cache.Add(c.key, c.val)
			val, ok := cache.Get(c.key)
			if !ok {
				t.Errorf("expected to find key")
				return
			}
			if string(val) != string(c.val) {
				t.Errorf("expected to find value")
				return
			}
		})
	}
}

func TestReapLoop(t *testing.T) {
	const baseTime = 5 * time.Millisecond
	const waitTime = baseTime + 5*time.Millisecond
	cache := pokecache.NewCache(baseTime)
	cache.Add("https://example.com", []byte("testdata"))

	_, ok := cache.Get("https://example.com")
	if !ok {
		t.Errorf("expected to find key")
		return
	}

	time.Sleep(waitTime)

	_, ok = cache.Get("https://example.com")
	if ok {
		t.Errorf("expected to not find key")
		return
	}
}


func TestGetMissingKey(t *testing.T) {
	const interval = 5 * time.Second
	cache := pokecache.NewCache(interval)

	_, ok := cache.Get("https://nonexistent.com")
	if ok {
		t.Errorf("expected to not find key")
		return
	}
}



func TestAddOverwritesExistingKey(t *testing.T) {
	const interval = 5 * time.Second
	cache := pokecache.NewCache(interval)

	cache.Add("key",[]byte("testdata"))
	cache.Add("key",[]byte("newdata"))

	val, ok := cache.Get("key")
	if !ok {
		t.Errorf("expected to find key")
		return
	}

	if string(val) != "newdata" {
		t.Errorf("expected value to be 'newdata', got %q", string(val))
		return
	}

}

func TestLocationDetails_UsesCache(t *testing.T) {
	// arrange
	cache := pokecache.NewCache(5 * time.Second)
	cfg := &nextBack{
		Cache: cache,
	}

	location := "test-area"
	locationURL := "https://pokeapi.co/api/v2/location-area/" + location + "/"

	// minimal valid JSON that matches AutoGenerated
	cachedJSON := []byte(`{
		"name": "test-area",
		"pokemon_encounters": []
	}`)

	// preload cache
	cache.Add(locationURL, cachedJSON)

	// act
	result, err := locationDetails(cfg, location)
	if err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	// assert
	if result.Name != "test-area" {
		t.Errorf("expected name 'test-area', got %q", result.Name)
	}
}

