package main

import (
	"encoding/json"
	"net/http"
	"fmt"
	"io"
)

type AutoGenerated struct {
	Name                 string                 `json:"name"`
	PokemonEncounters    []PokemonEncounters    `json:"pokemon_encounters"`
}

type Version struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}

type Pokemon struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}
type Method struct {
	Name string `json:"name"`
	URL  string `json:"url"`
}
type EncounterDetails struct {
	Chance          int    `json:"chance"`
	ConditionValues []any  `json:"condition_values"`
	MaxLevel        int    `json:"max_level"`
	Method          Method `json:"method"`
	MinLevel        int    `json:"min_level"`
}
type VersionDetails struct {
	EncounterDetails []EncounterDetails `json:"encounter_details"`
	MaxChance        int                `json:"max_chance"`
	Version          Version            `json:"version"`
}
type PokemonEncounters struct {
	Pokemon        Pokemon          `json:"pokemon"`
	VersionDetails []VersionDetails `json:"version_details"`
}

func locationDetails(cdg *nextBack,location string) (AutoGenerated,error){
	locationURL := "https://pokeapi.co/api/v2/location-area/" + location + "/"
	var lc AutoGenerated


	c := cdg.Cache
	ress, ok := c.Get(locationURL)
	if ok{
		fmt.Println("Cache resource being used...")
		err1 := json.Unmarshal(ress, &lc)
		if err1 != nil{
			return AutoGenerated{},err1
		}
		return lc,nil

	}


	req, err2 := http.NewRequest("GET",locationURL,nil)
	if err2 != nil{
		return  AutoGenerated{},err2
	}


	// client
	client := &http.Client{}
	res,err3 := client.Do(req)

	if err3 != nil{
		return AutoGenerated{},err3
	}

	defer res.Body.Close()

	respBytes, err4 := io.ReadAll(res.Body)
	if err4 != nil {
		return AutoGenerated{}, err4
	}

	c.Add(locationURL,respBytes)

	if err := json.Unmarshal(respBytes, &lc); err != nil {
		return AutoGenerated{}, err
	}
	return lc,nil

}



